# SPDX-License-Identifier: GPL-2.0-only

always-$(KBUILD_BUILTIN)	:= vmlinux.lds

obj-y := head.o setup.o process.o irq.o irqflags.o time.o \
	 signal.o syscall_table.o console.o initramfs_data.o asm-offsets.o
